// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: agent/agent.proto

package agent

import (
	context "context"
	common "github.com/dollarkillerx/go-proxy-manager/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	AddTask(ctx context.Context, in *common.TaskInfo, opts ...grpc.CallOption) (*common.Empty, error)
	ModifyTask(ctx context.Context, in *common.TaskInfo, opts ...grpc.CallOption) (*common.Empty, error)
	ApplyCertificate(ctx context.Context, in *ApplyCertificateReq, opts ...grpc.CallOption) (*common.Certificate, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) AddTask(ctx context.Context, in *common.TaskInfo, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/agent.Agent/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ModifyTask(ctx context.Context, in *common.TaskInfo, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/agent.Agent/ModifyTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ApplyCertificate(ctx context.Context, in *ApplyCertificateReq, opts ...grpc.CallOption) (*common.Certificate, error) {
	out := new(common.Certificate)
	err := c.cc.Invoke(ctx, "/agent.Agent/ApplyCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	AddTask(context.Context, *common.TaskInfo) (*common.Empty, error)
	ModifyTask(context.Context, *common.TaskInfo) (*common.Empty, error)
	ApplyCertificate(context.Context, *ApplyCertificateReq) (*common.Certificate, error)
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) AddTask(context.Context, *common.TaskInfo) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedAgentServer) ModifyTask(context.Context, *common.TaskInfo) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyTask not implemented")
}
func (UnimplementedAgentServer) ApplyCertificate(context.Context, *ApplyCertificateReq) (*common.Certificate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyCertificate not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddTask(ctx, req.(*common.TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ModifyTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ModifyTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/ModifyTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ModifyTask(ctx, req.(*common.TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ApplyCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyCertificateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ApplyCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/ApplyCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ApplyCertificate(ctx, req.(*ApplyCertificateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _Agent_AddTask_Handler,
		},
		{
			MethodName: "ModifyTask",
			Handler:    _Agent_ModifyTask_Handler,
		},
		{
			MethodName: "ApplyCertificate",
			Handler:    _Agent_ApplyCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/agent.proto",
}
