// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: backend/backend.proto

package backend

import (
	common "github.com/dollarkillerx/go-proxy-manager/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId               string  `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Ip                   string  `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	TasksNumber          int32   `protobuf:"varint,3,opt,name=tasksNumber,proto3" json:"tasksNumber,omitempty"`                   // 任务总数
	TasksAbnormalNumber  int32   `protobuf:"varint,4,opt,name=tasksAbnormalNumber,proto3" json:"tasksAbnormalNumber,omitempty"`   // 异常任务数
	TasksSuspendedNumber int32   `protobuf:"varint,5,opt,name=tasksSuspendedNumber,proto3" json:"tasksSuspendedNumber,omitempty"` // 暂停任务数
	Load                 float32 `protobuf:"fixed32,6,opt,name=load,proto3" json:"load,omitempty"`
	CpuInfo              string  `protobuf:"bytes,7,opt,name=cpuInfo,proto3" json:"cpuInfo,omitempty"`
	MemInfo              string  `protobuf:"bytes,8,opt,name=memInfo,proto3" json:"memInfo,omitempty"`
}

func (x *RgInfo) Reset() {
	*x = RgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgInfo) ProtoMessage() {}

func (x *RgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgInfo.ProtoReflect.Descriptor instead.
func (*RgInfo) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{0}
}

func (x *RgInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RgInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RgInfo) GetTasksNumber() int32 {
	if x != nil {
		return x.TasksNumber
	}
	return 0
}

func (x *RgInfo) GetTasksAbnormalNumber() int32 {
	if x != nil {
		return x.TasksAbnormalNumber
	}
	return 0
}

func (x *RgInfo) GetTasksSuspendedNumber() int32 {
	if x != nil {
		return x.TasksSuspendedNumber
	}
	return 0
}

func (x *RgInfo) GetLoad() float32 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *RgInfo) GetCpuInfo() string {
	if x != nil {
		return x.CpuInfo
	}
	return ""
}

func (x *RgInfo) GetMemInfo() string {
	if x != nil {
		return x.MemInfo
	}
	return ""
}

type RgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
}

func (x *RgResp) Reset() {
	*x = RgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RgResp) ProtoMessage() {}

func (x *RgResp) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RgResp.ProtoReflect.Descriptor instead.
func (*RgResp) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{1}
}

func (x *RgResp) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SyncDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Ip     string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *SyncDataReq) Reset() {
	*x = SyncDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataReq) ProtoMessage() {}

func (x *SyncDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataReq.ProtoReflect.Descriptor instead.
func (*SyncDataReq) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{2}
}

func (x *SyncDataReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncDataReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type SyncDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks []*common.TaskInfo `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
}

func (x *SyncDataResp) Reset() {
	*x = SyncDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDataResp) ProtoMessage() {}

func (x *SyncDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_backend_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDataResp.ProtoReflect.Descriptor instead.
func (*SyncDataResp) Descriptor() ([]byte, []int) {
	return file_backend_backend_proto_rawDescGZIP(), []int{3}
}

func (x *SyncDataResp) GetTasks() []*common.TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_backend_backend_proto protoreflect.FileDescriptor

var file_backend_backend_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02, 0x0a, 0x06, 0x52, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x13, 0x74, 0x61,
	0x73, 0x6b, 0x73, 0x41, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x41, 0x62,
	0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x14,
	0x74, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x53, 0x79,
	0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x22, 0x36, 0x0a, 0x0c, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x32, 0x70, 0x0a, 0x07, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x0f, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x0f, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x53,
	0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x6c, 0x6c, 0x61, 0x72,
	0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x78, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x3b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_backend_proto_rawDescOnce sync.Once
	file_backend_backend_proto_rawDescData = file_backend_backend_proto_rawDesc
)

func file_backend_backend_proto_rawDescGZIP() []byte {
	file_backend_backend_proto_rawDescOnce.Do(func() {
		file_backend_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_backend_proto_rawDescData)
	})
	return file_backend_backend_proto_rawDescData
}

var file_backend_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_backend_backend_proto_goTypes = []interface{}{
	(*RgInfo)(nil),          // 0: backend.RgInfo
	(*RgResp)(nil),          // 1: backend.RgResp
	(*SyncDataReq)(nil),     // 2: backend.SyncDataReq
	(*SyncDataResp)(nil),    // 3: backend.SyncDataResp
	(*common.TaskInfo)(nil), // 4: common.TaskInfo
}
var file_backend_backend_proto_depIdxs = []int32{
	4, // 0: backend.SyncDataResp.tasks:type_name -> common.TaskInfo
	0, // 1: backend.Backend.Register:input_type -> backend.RgInfo
	2, // 2: backend.Backend.SyncData:input_type -> backend.SyncDataReq
	1, // 3: backend.Backend.Register:output_type -> backend.RgResp
	3, // 4: backend.Backend.SyncData:output_type -> backend.SyncDataResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backend_backend_proto_init() }
func file_backend_backend_proto_init() {
	if File_backend_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_backend_proto_goTypes,
		DependencyIndexes: file_backend_backend_proto_depIdxs,
		MessageInfos:      file_backend_backend_proto_msgTypes,
	}.Build()
	File_backend_backend_proto = out.File
	file_backend_backend_proto_rawDesc = nil
	file_backend_backend_proto_goTypes = nil
	file_backend_backend_proto_depIdxs = nil
}
